services:
  database:
    image: mariadb:11.2.6-jammy
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: shopper
      MARIADB_PASSWORD: app
      MARIADB_USER: app
